version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: shopper-desafio-tecnico-db
    volumes:
      - db:/var/lib/postgresql/data
  
  app:
    container_name: fastify-app
    image: node:18
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npx prisma migrate dev && npm run db:seed && npm run dev"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      PORT: 3333
      CLOUDFLARE_ACCOUNT_ID: ${CLOUDFLARE_ACCOUNT_ID}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY_ID: ${AWS_SECRET_KEY_ID}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
    ports:
      - "3333:3333"

  cloudflare:
    container_name: cloudflare-container
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate --hostname local.dev --url http://fastify-app:3333
    environment:
      CLOUDFLARE_ACCOUNT_ID: ${CLOUDFLARE_ACCOUNT_ID}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY_ID: ${AWS_SECRET_KEY_ID}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
    depends_on:
      - app

volumes:
  db:
    driver: local
